.TH gtmess-gw 1 "December 19, 2004" "" "gtmess messenger http gateway"

.SH NAME
gtmess-gw - MSN messenger HTTP gateway

.SH SYNOPSIS
gtmess-gw [options]

.SH DESCRIPTION
.PP
gtmess-gw is an HTTP gateway for the MSN messenger protocol. It effectively emulates
an msn messenger server on the local machine and forwards all 
packets through the HTTP msn gateway (port 80).
This can be useful in cases there is a firewall that prevents access to ports other than 80.
It was written as a companion to the
.B gtmess
messenger client, but can be used with any other client.

.SH OPTIONS
.TP
.B -v
Verbose mode; error messages are written to stderr.

.SH BUGS

Some packets might be truncated. 

.SH SEE ALSO
.BR gtmess "(1), "
.BR gtmess-notify "(1)"


.SH AUTHORS

gtmess-gw - MSN messenger HTTP gateway
.br
Copyright (C) 2002-2004  George M. Tzoumas

.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
