.TH gtmess-notify 1 "August 22, 2010" "" "gtmess messenger notification popups"

.SH NAME
gtmess-notify - popup notification windows

.SH SYNOPSIS
gtmess-notify

.SH DESCRIPTION
.PP
gtmess-notify is a simple Tcl/Tk script that pops up notification
windows starting from the lower right corner of the screen. 
The script watches a named pipe for new lines and displays the contents of
each line in a separate popup window.
It was written as a companion to the
.B gtmess
messenger client, but could be of general use.

.SH EXAMPLE

First we start our daemon:

$ gtmess-notify &

Then we can popup anything, like:

$ echo "hello world" > ~/.gtmess/notify.pip

When we're done we can kill it:

$ killall gtmess-notify

.SH FILES
.TP
.B ~/.gtmess/notify.pip
The named pipe where the text to be displayed is read from. If
the file does not exist it is created. When the script catches a SIGINT
signal, it deletes the pipe and exits.

.SH SEE ALSO
.BR gtmess "(1), "
.BR gtmess\_w "(1), "
.BR notify-send "(1), "
.BR growlnotify "(1)"

.SH "BUGS"
Script fails to remove the pipe upon SIGTERM (at least in Darwin). 

.SH CREDITS

Inspired from the aMSN messenger client.

.SH AUTHORS

gtmess-notify - popup notification windows
.br
Copyright (C) 2002-2004,2010  George M. Tzoumas

.PP
This script is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.PP
The source code of this script is ABSOLUTELY FREE.
You can do whatever you want with it ;-)
